# Generated by Django 3.2.8 on 2021-10-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lawtable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=500)),
                ('caseId', models.IntegerField()),
                ('caseSection', models.CharField(max_length=500)),
                ('caseDetails', models.CharField(max_length=500)),
                ('caseType', models.CharField(max_length=500)),
            ],
        ),
    ]
